//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pesedjet.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pesedjet.Client.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account now.
        /// </summary>
        internal static string AccessMenu_CreateAccount {
            get {
                return ResourceManager.GetString("AccessMenu.CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string AccessMenu_ForgottenPassword {
            get {
                return ResourceManager.GetString("AccessMenu.ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string AccessMenu_LogIn {
            get {
                return ResourceManager.GetString("AccessMenu.LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string AccessMenu_NewAccountMessage {
            get {
                return ResourceManager.GetString("AccessMenu.NewAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AccessMenu_Password {
            get {
                return ResourceManager.GetString("AccessMenu.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as Guest.
        /// </summary>
        internal static string AccessMenu_PlayAsGuest {
            get {
                return ResourceManager.GetString("AccessMenu.PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AccessMenu_Username {
            get {
                return ResourceManager.GetString("AccessMenu.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string AccessMenu_WelcomeMessage {
            get {
                return ResourceManager.GetString("AccessMenu.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked players list.
        /// </summary>
        internal static string BlockedPlayersSection_BlockedPlayersMessage {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.BlockedPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string BlockedPlayersSection_Unblock {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ForgotPassword_ButtonCancel {
            get {
                return ResourceManager.GetString("ForgotPassword.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ForgotPassword_ButtonReset {
            get {
                return ResourceManager.GetString("ForgotPassword.ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        internal static string ForgotPassword_ButtonSendCode {
            get {
                return ResourceManager.GetString("ForgotPassword.ButtonSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        internal static string ForgotPassword_Code {
            get {
                return ResourceManager.GetString("ForgotPassword.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string ForgotPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ForgotPassword.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code must contain exactly 6 numeric digits..
        /// </summary>
        internal static string ForgotPassword_Error_InvalidCode {
            get {
                return ResourceManager.GetString("ForgotPassword.Error.InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string ForgotPassword_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("ForgotPassword.Error.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters, include an uppercase letter, a number, a special character, and both fields must match..
        /// </summary>
        internal static string ForgotPassword_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("ForgotPassword.Error.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address associated with your account to receive a verification code..
        /// </summary>
        internal static string ForgotPassword_InstructionStep1 {
            get {
                return ResourceManager.GetString("ForgotPassword.InstructionStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6-digit code sent to your email and your new password..
        /// </summary>
        internal static string ForgotPassword_InstructionStep2 {
            get {
                return ResourceManager.GetString("ForgotPassword.InstructionStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string ForgotPassword_NewPassword {
            get {
                return ResourceManager.GetString("ForgotPassword.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated..
        /// </summary>
        internal static string ForgotPassword_SuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPassword.SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string FriendsListSection_Accept {
            get {
                return ResourceManager.GetString("FriendsListSection.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string FriendsListSection_Block {
            get {
                return ResourceManager.GetString("FriendsListSection.Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no added friends yet. Go to the &apos;Add new friend&apos; tab to search for players..
        /// </summary>
        internal static string FriendsListSection_EmptyList {
            get {
                return ResourceManager.GetString("FriendsListSection.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See profile.
        /// </summary>
        internal static string FriendsListSection_FriendProfile {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends List.
        /// </summary>
        internal static string FriendsListSection_FriendsListMessage {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendsListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string FriendsListSection_Reject {
            get {
                return ResourceManager.GetString("FriendsListSection.Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string FriendsListSection_Remove {
            get {
                return ResourceManager.GetString("FriendsListSection.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added friends.
        /// </summary>
        internal static string FriendsSection_AddedFriends {
            get {
                return ResourceManager.GetString("FriendsSection.AddedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked players.
        /// </summary>
        internal static string FriendsSection_BlockedPlayers {
            get {
                return ResourceManager.GetString("FriendsSection.BlockedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new friend.
        /// </summary>
        internal static string FriendsSection_NewFriend {
            get {
                return ResourceManager.GetString("FriendsSection.NewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the invitation code.
        /// </summary>
        internal static string JoinMatch_EnterCode {
            get {
                return ResourceManager.GetString("JoinMatch.EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match for this room has already started and does not accept new players..
        /// </summary>
        internal static string JoinMatch_Error_GameInProgress {
            get {
                return ResourceManager.GetString("JoinMatch.Error.GameInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 6-character room code..
        /// </summary>
        internal static string JoinMatch_Error_InvalidCodeFormat {
            get {
                return ResourceManager.GetString("JoinMatch.Error.InvalidCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected room has reached its maximum capacity..
        /// </summary>
        internal static string JoinMatch_Error_RoomFull {
            get {
                return ResourceManager.GetString("JoinMatch.Error.RoomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game room was found associated with the entered code..
        /// </summary>
        internal static string JoinMatch_Error_RoomNotFound {
            get {
                return ResourceManager.GetString("JoinMatch.Error.RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public rooms available at this moment..
        /// </summary>
        internal static string JoinMatch_NoPublicRooms {
            get {
                return ResourceManager.GetString("JoinMatch.NoPublicRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Code.
        /// </summary>
        internal static string JoinMatch_TabCode {
            get {
                return ResourceManager.GetString("JoinMatch.TabCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Public Rooms.
        /// </summary>
        internal static string JoinMatch_TabPublicRooms {
            get {
                return ResourceManager.GetString("JoinMatch.TabPublicRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string Leaderboard_ActionProfile {
            get {
                return ResourceManager.GetString("Leaderboard.ActionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulets Earned.
        /// </summary>
        internal static string Leaderboard_Amulets {
            get {
                return ResourceManager.GetString("Leaderboard.Amulets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scores recorded in the selected category yet..
        /// </summary>
        internal static string Leaderboard_Empty {
            get {
                return ResourceManager.GetString("Leaderboard.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Leaderboard_FilterAll {
            get {
                return ResourceManager.GetString("Leaderboard.FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Only.
        /// </summary>
        internal static string Leaderboard_FilterFriends {
            get {
                return ResourceManager.GetString("Leaderboard.FilterFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Leaderboard_Player {
            get {
                return ResourceManager.GetString("Leaderboard.Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Leaderboard_Rank {
            get {
                return ResourceManager.GetString("Leaderboard.Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        internal static string Leaderboard_Title {
            get {
                return ResourceManager.GetString("Leaderboard.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Won.
        /// </summary>
        internal static string Leaderboard_Victories {
            get {
                return ResourceManager.GetString("Leaderboard.Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURE YOUR GAME:.
        /// </summary>
        internal static string Match_ConfigureTitle {
            get {
                return ResourceManager.GetString("Match.ConfigureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create room.
        /// </summary>
        internal static string Match_Create {
            get {
                return ResourceManager.GetString("Match.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string Match_CreateNew {
            get {
                return ResourceManager.GetString("Match.CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Match_Join {
            get {
                return ResourceManager.GetString("Match.Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        internal static string Match_Players {
            get {
                return ResourceManager.GetString("Match.Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Privacy:.
        /// </summary>
        internal static string Match_Privacy {
            get {
                return ResourceManager.GetString("Match.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Match_PrivacyPrivate {
            get {
                return ResourceManager.GetString("Match.PrivacyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Match_PrivacyPublic {
            get {
                return ResourceManager.GetString("Match.PrivacyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Match_Type {
            get {
                return ResourceManager.GetString("Match.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Match_TypeFast {
            get {
                return ResourceManager.GetString("Match.TypeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Match_TypeNormal {
            get {
                return ResourceManager.GetString("Match.TypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Menu_Friends {
            get {
                return ResourceManager.GetString("Menu.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending friends request.
        /// </summary>
        internal static string Menu_FriendsRequest {
            get {
                return ResourceManager.GetString("Menu.FriendsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary and Game Rules.
        /// </summary>
        internal static string Menu_GlossaryAndRulesMessage {
            get {
                return ResourceManager.GetString("Menu.GlossaryAndRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        internal static string Menu_Leaderboard {
            get {
                return ResourceManager.GetString("Menu.Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu.LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Menu_MyLevel {
            get {
                return ResourceManager.GetString("Menu.MyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my profile.
        /// </summary>
        internal static string Menu_MyProfile {
            get {
                return ResourceManager.GetString("Menu.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Menu_MyRank {
            get {
                return ResourceManager.GetString("Menu.MyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Menu_Play {
            get {
                return ResourceManager.GetString("Menu.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending room invitations.
        /// </summary>
        internal static string Menu_RoomInvitations {
            get {
                return ResourceManager.GetString("Menu.RoomInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pantheon War.
        /// </summary>
        internal static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesedjet.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string NewFriend_AddFriend {
            get {
                return ResourceManager.GetString("NewFriend.AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string NewFriend_NewFriendMessage {
            get {
                return ResourceManager.GetString("NewFriend.NewFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Setup.
        /// </summary>
        internal static string PlaySection_ConfigureMatch {
            get {
                return ResourceManager.GetString("PlaySection.ConfigureMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string PlaySection_ConfirmCreate {
            get {
                return ResourceManager.GetString("PlaySection.ConfirmCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type:.
        /// </summary>
        internal static string PlaySection_GameType {
            get {
                return ResourceManager.GetString("PlaySection.GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        internal static string PlaySection_GameTypeQuick {
            get {
                return ResourceManager.GetString("PlaySection.GameTypeQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string PlaySection_GameTypeStandard {
            get {
                return ResourceManager.GetString("PlaySection.GameTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string PlaySection_JoinMatch {
            get {
                return ResourceManager.GetString("PlaySection.JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        internal static string PlaySection_NewMatch {
            get {
                return ResourceManager.GetString("PlaySection.NewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players:.
        /// </summary>
        internal static string PlaySection_PlayerCount {
            get {
                return ResourceManager.GetString("PlaySection.PlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string PlaySection_PrivateScope {
            get {
                return ResourceManager.GetString("PlaySection.PrivateScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string PlaySection_PublicScope {
            get {
                return ResourceManager.GetString("PlaySection.PublicScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room privacy:.
        /// </summary>
        internal static string PlaySection_RoomPrivacy {
            get {
                return ResourceManager.GetString("PlaySection.RoomPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Profile_BirthDate {
            get {
                return ResourceManager.GetString("Profile.BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Profile_FullName {
            get {
                return ResourceManager.GetString("Profile.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Profile_Gametag {
            get {
                return ResourceManager.GetString("Profile.Gametag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Register_BirthDate {
            get {
                return ResourceManager.GetString("Register.BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Register_ButtonCancel {
            get {
                return ResourceManager.GetString("Register.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register_ButtonSubmit {
            get {
                return ResourceManager.GetString("Register.ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Register_Email {
            get {
                return ResourceManager.GetString("Register.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email address is already associated with an account..
        /// </summary>
        internal static string Register_Error_EmailInUse {
            get {
                return ResourceManager.GetString("Register.Error.EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is unavailable. Please choose another one..
        /// </summary>
        internal static string Register_Error_GametagInUse {
            get {
                return ResourceManager.GetString("Register.Error.GametagInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters, include an uppercase letter, a number, a special character, and both fields must match..
        /// </summary>
        internal static string Register_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Register.Error.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields with the correct format..
        /// </summary>
        internal static string Register_Error_RequiredFields {
            get {
                return ResourceManager.GetString("Register.Error.RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is only allowed for individuals who are 12 years of age or older..
        /// </summary>
        internal static string Register_Error_Underage {
            get {
                return ResourceManager.GetString("Register.Error.Underage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Register_FullName {
            get {
                return ResourceManager.GetString("Register.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (Gametag).
        /// </summary>
        internal static string Register_Gametag {
            get {
                return ResourceManager.GetString("Register.Gametag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Register_Password {
            get {
                return ResourceManager.GetString("Register.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Settings_Music {
            get {
                return ResourceManager.GetString("Settings.Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_SectionMessage {
            get {
                return ResourceManager.GetString("Settings.SectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings.Sound", resourceCulture);
            }
        }
        
        internal static string AccessMenu_LoginSuccess {
            get {
                return ResourceManager.GetString("AccessMenu.LoginSuccess", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TwoFactor_ButtonCancel {
            get {
                return ResourceManager.GetString("TwoFactor.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string TwoFactor_ButtonResend {
            get {
                return ResourceManager.GetString("TwoFactor.ButtonResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string TwoFactor_ButtonVerify {
            get {
                return ResourceManager.GetString("TwoFactor.ButtonVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has expired. Please request a new one..
        /// </summary>
        internal static string TwoFactor_Error_ExpiredCode {
            get {
                return ResourceManager.GetString("TwoFactor.Error.ExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code is incorrect. Please try again..
        /// </summary>
        internal static string TwoFactor_Error_IncorrectCode {
            get {
                return ResourceManager.GetString("TwoFactor.Error.IncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code must contain exactly 6 numeric digits..
        /// </summary>
        internal static string TwoFactor_Error_InvalidCodeLength {
            get {
                return ResourceManager.GetString("TwoFactor.Error.InvalidCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6-digit code sent to your email. The code expires in:.
        /// </summary>
        internal static string TwoFactor_Instruction {
            get {
                return ResourceManager.GetString("TwoFactor.Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new verification code has been sent to your email..
        /// </summary>
        internal static string TwoFactor_ResendSuccess {
            get {
                return ResourceManager.GetString("TwoFactor.ResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Verification.
        /// </summary>
        internal static string TwoFactor_Title {
            get {
                return ResourceManager.GetString("TwoFactor.Title", resourceCulture);
            }
        }
    }
}
