//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pesedjet.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pesedjet.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una nueva cuenta ahora.
        /// </summary>
        internal static string AccessMenu_CreateAccount {
            get {
                return ResourceManager.GetString("AccessMenu.CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste la contraseña?.
        /// </summary>
        internal static string AccessMenu_ForgottenPassword {
            get {
                return ResourceManager.GetString("AccessMenu.ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string AccessMenu_LogIn {
            get {
                return ResourceManager.GetString("AccessMenu.LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta?.
        /// </summary>
        internal static string AccessMenu_NewAccountMessage {
            get {
                return ResourceManager.GetString("AccessMenu.NewAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string AccessMenu_Password {
            get {
                return ResourceManager.GetString("AccessMenu.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como Invitado.
        /// </summary>
        internal static string AccessMenu_PlayAsGuest {
            get {
                return ResourceManager.GetString("AccessMenu.PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string AccessMenu_Username {
            get {
                return ResourceManager.GetString("AccessMenu.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string AccessMenu_WelcomeMessage {
            get {
                return ResourceManager.GetString("AccessMenu.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de jugadores bloqueados.
        /// </summary>
        internal static string BlockedPlayersSection_BlockedPlayersMessage {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.BlockedPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        internal static string BlockedPlayersSection_Unblock {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string FriendsListSection_Accept {
            get {
                return ResourceManager.GetString("FriendsListSection.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear.
        /// </summary>
        internal static string FriendsListSection_Block {
            get {
                return ResourceManager.GetString("FriendsListSection.Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes amigos agregados aún. Ve a la pestaña &apos;Añadir nuevo amigo&apos; para buscar jugadores..
        /// </summary>
        internal static string FriendsListSection_EmptyList {
            get {
                return ResourceManager.GetString("FriendsListSection.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver perfil.
        /// </summary>
        internal static string FriendsListSection_FriendProfile {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de amigos.
        /// </summary>
        internal static string FriendsListSection_FriendsListMessage {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendsListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string FriendsListSection_Reject {
            get {
                return ResourceManager.GetString("FriendsListSection.Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string FriendsListSection_Remove {
            get {
                return ResourceManager.GetString("FriendsListSection.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amistades añadidas.
        /// </summary>
        internal static string FriendsSection_AddedFriends {
            get {
                return ResourceManager.GetString("FriendsSection.AddedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores bloqueados.
        /// </summary>
        internal static string FriendsSection_BlockedPlayers {
            get {
                return ResourceManager.GetString("FriendsSection.BlockedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo amigo.
        /// </summary>
        internal static string FriendsSection_NewFriend {
            get {
                return ResourceManager.GetString("FriendsSection.NewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURA TU PARTIDA:.
        /// </summary>
        internal static string Match_ConfigureTitle {
            get {
                return ResourceManager.GetString("Match.ConfigureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear sala.
        /// </summary>
        internal static string Match_Create {
            get {
                return ResourceManager.GetString("Match.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nueva.
        /// </summary>
        internal static string Match_CreateNew {
            get {
                return ResourceManager.GetString("Match.CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        internal static string Match_Join {
            get {
                return ResourceManager.GetString("Match.Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores:.
        /// </summary>
        internal static string Match_Players {
            get {
                return ResourceManager.GetString("Match.Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidad del juego:.
        /// </summary>
        internal static string Match_Privacy {
            get {
                return ResourceManager.GetString("Match.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privada.
        /// </summary>
        internal static string Match_PrivacyPrivate {
            get {
                return ResourceManager.GetString("Match.PrivacyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pública.
        /// </summary>
        internal static string Match_PrivacyPublic {
            get {
                return ResourceManager.GetString("Match.PrivacyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo:.
        /// </summary>
        internal static string Match_Type {
            get {
                return ResourceManager.GetString("Match.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rápida.
        /// </summary>
        internal static string Match_TypeFast {
            get {
                return ResourceManager.GetString("Match.TypeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Match_TypeNormal {
            get {
                return ResourceManager.GetString("Match.TypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        internal static string Menu_Friends {
            get {
                return ResourceManager.GetString("Menu.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes de amistad pendientes.
        /// </summary>
        internal static string Menu_FriendsRequest {
            get {
                return ResourceManager.GetString("Menu.FriendsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glosario y Reglas de Juego.
        /// </summary>
        internal static string Menu_GlossaryAndRulesMessage {
            get {
                return ResourceManager.GetString("Menu.GlossaryAndRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcador de puntuación.
        /// </summary>
        internal static string Menu_Leaderboard {
            get {
                return ResourceManager.GetString("Menu.Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu.LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        internal static string Menu_MyLevel {
            get {
                return ResourceManager.GetString("Menu.MyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver mi perfil.
        /// </summary>
        internal static string Menu_MyProfile {
            get {
                return ResourceManager.GetString("Menu.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango.
        /// </summary>
        internal static string Menu_MyRank {
            get {
                return ResourceManager.GetString("Menu.MyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar.
        /// </summary>
        internal static string Menu_Play {
            get {
                return ResourceManager.GetString("Menu.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitaciones a sala de juego.
        /// </summary>
        internal static string Menu_RoomInvitations {
            get {
                return ResourceManager.GetString("Menu.RoomInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Guerra del Panteón.
        /// </summary>
        internal static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesedjet.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo amigo.
        /// </summary>
        internal static string NewFriend_AddFriend {
            get {
                return ResourceManager.GetString("NewFriend.AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el nombre de usuario.
        /// </summary>
        internal static string NewFriend_NewFriendMessage {
            get {
                return ResourceManager.GetString("NewFriend.NewFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musica.
        /// </summary>
        internal static string Settings_Music {
            get {
                return ResourceManager.GetString("Settings.Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings_SectionMessage {
            get {
                return ResourceManager.GetString("Settings.SectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonido.
        /// </summary>
        internal static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings.Sound", resourceCulture);
            }
        }
        
        internal static string AccessMenu_LoginSuccess {
            get {
                return ResourceManager.GetString("AccessMenu.LoginSuccess", resourceCulture);
            }
        }
    }
}
