//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pesedjet.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pesedjet.Client.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account now.
        /// </summary>
        internal static string AccessMenu_CreateAccount {
            get {
                return ResourceManager.GetString("AccessMenu.CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string AccessMenu_ForgottenPassword {
            get {
                return ResourceManager.GetString("AccessMenu.ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string AccessMenu_LogIn {
            get {
                return ResourceManager.GetString("AccessMenu.LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string AccessMenu_NewAccountMessage {
            get {
                return ResourceManager.GetString("AccessMenu.NewAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AccessMenu_Password {
            get {
                return ResourceManager.GetString("AccessMenu.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as Guest.
        /// </summary>
        internal static string AccessMenu_PlayAsGuest {
            get {
                return ResourceManager.GetString("AccessMenu.PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AccessMenu_Username {
            get {
                return ResourceManager.GetString("AccessMenu.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string AccessMenu_WelcomeMessage {
            get {
                return ResourceManager.GetString("AccessMenu.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked players list.
        /// </summary>
        internal static string BlockedPlayersSection_BlockedPlayersMessage {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.BlockedPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string BlockedPlayersSection_Unblock {
            get {
                return ResourceManager.GetString("BlockedPlayersSection.Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string FriendsListSection_Accept {
            get {
                return ResourceManager.GetString("FriendsListSection.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string FriendsListSection_Block {
            get {
                return ResourceManager.GetString("FriendsListSection.Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no added friends yet. Go to the &apos;Add new friend&apos; tab to search for players..
        /// </summary>
        internal static string FriendsListSection_EmptyList {
            get {
                return ResourceManager.GetString("FriendsListSection.EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See profile.
        /// </summary>
        internal static string FriendsListSection_FriendProfile {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends List.
        /// </summary>
        internal static string FriendsListSection_FriendsListMessage {
            get {
                return ResourceManager.GetString("FriendsListSection.FriendsListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string FriendsListSection_Reject {
            get {
                return ResourceManager.GetString("FriendsListSection.Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string FriendsListSection_Remove {
            get {
                return ResourceManager.GetString("FriendsListSection.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added friends.
        /// </summary>
        internal static string FriendsSection_AddedFriends {
            get {
                return ResourceManager.GetString("FriendsSection.AddedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked players.
        /// </summary>
        internal static string FriendsSection_BlockedPlayers {
            get {
                return ResourceManager.GetString("FriendsSection.BlockedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new friend.
        /// </summary>
        internal static string FriendsSection_NewFriend {
            get {
                return ResourceManager.GetString("FriendsSection.NewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURE YOUR GAME:.
        /// </summary>
        internal static string Match_ConfigureTitle {
            get {
                return ResourceManager.GetString("Match.ConfigureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create room.
        /// </summary>
        internal static string Match_Create {
            get {
                return ResourceManager.GetString("Match.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        internal static string Match_CreateNew {
            get {
                return ResourceManager.GetString("Match.CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Match_Join {
            get {
                return ResourceManager.GetString("Match.Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        internal static string Match_Players {
            get {
                return ResourceManager.GetString("Match.Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Privacy:.
        /// </summary>
        internal static string Match_Privacy {
            get {
                return ResourceManager.GetString("Match.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Match_PrivacyPrivate {
            get {
                return ResourceManager.GetString("Match.PrivacyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Match_PrivacyPublic {
            get {
                return ResourceManager.GetString("Match.PrivacyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Match_Type {
            get {
                return ResourceManager.GetString("Match.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Match_TypeFast {
            get {
                return ResourceManager.GetString("Match.TypeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Match_TypeNormal {
            get {
                return ResourceManager.GetString("Match.TypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Menu_Friends {
            get {
                return ResourceManager.GetString("Menu.Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending friends request.
        /// </summary>
        internal static string Menu_FriendsRequest {
            get {
                return ResourceManager.GetString("Menu.FriendsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary and Game Rules.
        /// </summary>
        internal static string Menu_GlossaryAndRulesMessage {
            get {
                return ResourceManager.GetString("Menu.GlossaryAndRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        internal static string Menu_Leaderboard {
            get {
                return ResourceManager.GetString("Menu.Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu.LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Menu_MyLevel {
            get {
                return ResourceManager.GetString("Menu.MyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my profile.
        /// </summary>
        internal static string Menu_MyProfile {
            get {
                return ResourceManager.GetString("Menu.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Menu_MyRank {
            get {
                return ResourceManager.GetString("Menu.MyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Menu_Play {
            get {
                return ResourceManager.GetString("Menu.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending room invitations.
        /// </summary>
        internal static string Menu_RoomInvitations {
            get {
                return ResourceManager.GetString("Menu.RoomInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pantheon War.
        /// </summary>
        internal static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesedjet.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string NewFriend_AddFriend {
            get {
                return ResourceManager.GetString("NewFriend.AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username.
        /// </summary>
        internal static string NewFriend_NewFriendMessage {
            get {
                return ResourceManager.GetString("NewFriend.NewFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Settings_Music {
            get {
                return ResourceManager.GetString("Settings.Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_SectionMessage {
            get {
                return ResourceManager.GetString("Settings.SectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings.Sound", resourceCulture);
            }
        }
    }
}
