//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pesedjet.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pesedjet.Client.Resources.Strings_en_US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccessMenu_CreateAccount {
            get {
                return ResourceManager.GetString("AccessMenu.CreateAccount", resourceCulture);
            }
        }
        
        internal static string AccessMenu_ForgottenPassword {
            get {
                return ResourceManager.GetString("AccessMenu.ForgottenPassword", resourceCulture);
            }
        }
        
        internal static string AccessMenu_LogIn {
            get {
                return ResourceManager.GetString("AccessMenu.LogIn", resourceCulture);
            }
        }
        
        internal static string AccessMenu_NewAccountMessage {
            get {
                return ResourceManager.GetString("AccessMenu.NewAccountMessage", resourceCulture);
            }
        }
        
        internal static string AccessMenu_Password {
            get {
                return ResourceManager.GetString("AccessMenu.Password", resourceCulture);
            }
        }
        
        internal static string AccessMenu_PlayAsGuest {
            get {
                return ResourceManager.GetString("AccessMenu.PlayAsGuest", resourceCulture);
            }
        }
        
        internal static string AccessMenu_Username {
            get {
                return ResourceManager.GetString("AccessMenu.Username", resourceCulture);
            }
        }
        
        internal static string AccessMenu_WelcomeMessage {
            get {
                return ResourceManager.GetString("AccessMenu.WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        internal static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu.Subtitle", resourceCulture);
            }
        }
        
        internal static string Menu_FriendsRequest {
            get {
                return ResourceManager.GetString("Menu.FriendsRequest", resourceCulture);
            }
        }
        
        internal static string Menu_RoomInvitations {
            get {
                return ResourceManager.GetString("Menu.RoomInvitations", resourceCulture);
            }
        }
        
        internal static string Menu_Friends {
            get {
                return ResourceManager.GetString("Menu.Friends", resourceCulture);
            }
        }
        
        internal static string Menu_Leaderboard {
            get {
                return ResourceManager.GetString("Menu.Leaderboard", resourceCulture);
            }
        }
        
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu.LogOut", resourceCulture);
            }
        }
        
        internal static string Menu_Play {
            get {
                return ResourceManager.GetString("Menu.Play", resourceCulture);
            }
        }
        
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        internal static string Menu_MyProfile {
            get {
                return ResourceManager.GetString("Menu.MyProfile", resourceCulture);
            }
        }
        
        internal static string Menu_GlossaryAndRulesMessage {
            get {
                return ResourceManager.GetString("Menu.GlossaryAndRulesMessage", resourceCulture);
            }
        }
        
        internal static string Menu_MyLevel {
            get {
                return ResourceManager.GetString("Menu.MyLevel", resourceCulture);
            }
        }
        
        internal static string Menu_MyRank {
            get {
                return ResourceManager.GetString("Menu.MyRank", resourceCulture);
            }
        }
        
        internal static string Settings_SectionMessage {
            get {
                return ResourceManager.GetString("Settings.SectionMessage", resourceCulture);
            }
        }
        
        internal static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings.Sound", resourceCulture);
            }
        }
        
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        internal static string Settings_Music {
            get {
                return ResourceManager.GetString("Settings.Music", resourceCulture);
            }
        }
        
        internal static string Match_CreateNew {
            get {
                return ResourceManager.GetString("Match.CreateNew", resourceCulture);
            }
        }
        
        internal static string Match_Join {
            get {
                return ResourceManager.GetString("Match.Join", resourceCulture);
            }
        }
        
        internal static string Match_Create {
            get {
                return ResourceManager.GetString("Match.Create", resourceCulture);
            }
        }
        
        internal static string Match_ConfigureTitle {
            get {
                return ResourceManager.GetString("Match.ConfigureTitle", resourceCulture);
            }
        }
        
        internal static string Match_Players {
            get {
                return ResourceManager.GetString("Match.Players", resourceCulture);
            }
        }
        
        internal static string Match_Privacy {
            get {
                return ResourceManager.GetString("Match.Privacy", resourceCulture);
            }
        }
        
        internal static string Match_PrivacyPrivate {
            get {
                return ResourceManager.GetString("Match.PrivacyPrivate", resourceCulture);
            }
        }
        
        internal static string Match_PrivacyPublic {
            get {
                return ResourceManager.GetString("Match.PrivacyPublic", resourceCulture);
            }
        }
        
        internal static string Match_Type {
            get {
                return ResourceManager.GetString("Match.Type", resourceCulture);
            }
        }
        
        internal static string Match_TypeFast {
            get {
                return ResourceManager.GetString("Match.TypeFast", resourceCulture);
            }
        }
        
        internal static string Match_TypeNormal {
            get {
                return ResourceManager.GetString("Match.TypeNormal", resourceCulture);
            }
        }
    }
}
